// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7rEQU_alREGWMoindss6HGvQ1xsYsXI',
    appId: '1:1018422104789:web:89baecb0c69c4a478a485c',
    messagingSenderId: '1018422104789',
    projectId: 'fooderapp-89436',
    authDomain: 'fooderapp-89436.firebaseapp.com',
    databaseURL:
        'https://fooderapp-89436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooderapp-89436.firebasestorage.app',
    measurementId: 'G-VQD2L8GFDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPB3uU2w8e5XOKoXS_DQh-XwOHSCUTCs',
    appId: '1:1018422104789:android:e05efee8cb99237c8a485c',
    messagingSenderId: '1018422104789',
    projectId: 'fooderapp-89436',
    databaseURL:
        'https://fooderapp-89436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooderapp-89436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpF1pvMI6frAcSw8kzkiLQUphlqqVoinE',
    appId: '1:1018422104789:ios:4ae8fa0f294fb52d8a485c',
    messagingSenderId: '1018422104789',
    projectId: 'fooderapp-89436',
    databaseURL:
        'https://fooderapp-89436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooderapp-89436.firebasestorage.app',
    iosClientId:
        '1018422104789-j10j61amn66ldmrvpgv7p22eta4qdh69.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodorderApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn7rEQU_alREGWMoindss6HGvQ1xsYsXI',
    appId: '1:1018422104789:web:89baecb0c69c4a478a485c',
    messagingSenderId: '1018422104789',
    projectId: 'fooderapp-89436',
    authDomain: 'fooderapp-89436.firebaseapp.com',
    storageBucket: 'fooderapp-89436.firebasestorage.app',
    measurementId: 'G-VQD2L8GFDK',
  );
}
